version: '2'
services:
  razilomvcs:
    build: ./
    container_name: razilomvcs
    labels:
      - "traefik.backend=razilomvcs"
      - "traefik.frontend.rule=Host:razilomvcs.docker.localhost"
    volumes:
      - ./config:/app/config
      - ./public:/app/public
      - ./src:/app/src
      - ./logs:/app/logs
      - ./index.mjs:/app/index.mjs
      - ./package.json:/app/package.json
    networks:
      - default
    environment:
      - SOMETHING=600 #In seconds
networks:
  default:
    external:
      name: docker_docker-localhost
